[project]
name = "lightning-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "lightning-client-mcp>=0.0.1",
    "mcp[cli]>=1.6.0",
]
